# Generated by Django 2.2.20 on 2021-05-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('venue', models.CharField(max_length=15)),
            ],
        ),
    ]
