# Generated by Django 2.2.20 on 2021-05-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
