# Generated by Django 2.2.20 on 2021-05-18 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0002_eventmodel_contact_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='contact_phone_number',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='event_head',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='hosted_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='EventRegistartion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('time', models.TimeField()),
                ('date', models.DateField(null=True)),
                ('venue', models.CharField(max_length=15)),
                ('contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('event_head', models.CharField(blank=True, max_length=30, null=True)),
                ('hosted_by', models.CharField(blank=True, max_length=30, null=True)),
                ('created_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
