# Generated by Django 2.2.20 on 2021-05-18 17:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210518_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='date',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='description',
            new_name='event_description',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='hosted_by',
            new_name='event_hosted_by',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='image',
            new_name='event_image',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='time',
            new_name='event_time',
        ),
        migrations.RenameField(
            model_name='eventmodel',
            old_name='venue',
            new_name='event_venue',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
