# Generated by Django 2.2.20 on 2021-05-19 03:40

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210518_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='contact_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistartion',
            name='contact_phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
