# Generated by Django 2.2.20 on 2021-05-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210519_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregistartion',
            old_name='contact_phone_number',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='eventregistartion',
            old_name='date',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='eventregistartion',
            old_name='hosted_by',
            new_name='event_hosted_by',
        ),
        migrations.RenameField(
            model_name='eventregistartion',
            old_name='time',
            new_name='event_time',
        ),
        migrations.RenameField(
            model_name='eventregistartion',
            old_name='venue',
            new_name='event_venue',
        ),
        migrations.RemoveField(
            model_name='eventregistartion',
            name='image',
        ),
        migrations.AddField(
            model_name='eventregistartion',
            name='event_description',
            field=models.TextField(default='this is'),
        ),
        migrations.AddField(
            model_name='eventregistartion',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eventregistartion',
            name='total_seats',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
