# Generated by Django 2.2.20 on 2021-05-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='event',
        ),
        migrations.AddField(
            model_name='profile',
            name='event',
            field=models.ManyToManyField(to='student.OrderEvent'),
        ),
    ]
