# Generated by Django 2.2.20 on 2021-05-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20210523_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
